apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: AuthSystem
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - AuthSystem.example.com
    secretName: AuthSystem-tls
  rules:
  - host: AuthSystem.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: AuthSystem
            port:
              number: 80
