apiVersion: v1
kind: Secret
metadata:
  name: AuthSystem-secret
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres:5432/AuthSystem"
  jwt-secret: "your-jwt-secret-here"
  api-key: "your-api-key-here"
